name: Build and Release to ghcr.io

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker buildx build --push \
            -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest \
            -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }} \
            .
